#!/bin/bash

run() {
    echo "Starting services with Docker Compose..."
    docker-compose -f "$1" up
}

welcome=$(cat <<-EOF
GradeForge is a tool to automatically generate student report cards using large
language models.

To run this service, make sure the following are true:
1. Docker compose is installed
  - installation instructions: https://docs.docker.com/compose/install/.

2. The correct environment variables are set
  - depending on the generative model you decide to use, set the appropriate
    credentials in the .env file in this folder.

Now you can run the service using the following command:
./gradeforge [ollama|claude]

Have fun! Report any issues here:
https://github.com/dannowilby/gradeforge/issues
EOF
)

case ${1,,} in
    "help" | "")
        echo "$welcome" ;;
    "ollama")
        echo "Selected generation model: Ollama (local)" && run "build/compose-ollama.yaml" ;;
    "claude")
        echo "Selected generation model: Claude (api)" && run "build/compose-claude.yaml" ;;
esac
