# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/student_details.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'proto/student_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/student_details.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n\x0eStudentDetails\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x14\n\x0cstudent_name\x18\x02 \x01(\t\x12\x0f\n\x07onboard\x18\x03 \x01(\x08\x12:\n\x11\x62\x65havior_comments\x18\x04 \x03(\x0b\x32\x1f.StudentDetails.BehaviorComment\x12\x19\n\x11total_plan_length\x18\x05 \x01(\r\x12/\n\x0fupdated_lessons\x18\x06 \x03(\x0b\x32\x16.StudentDetails.Lesson\x1a\x65\n\x0f\x42\x65haviorComment\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x17\n\x0fpages_completed\x18\x03 \x01(\r\x1a)\n\x06Lesson\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.student_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTDETAILS']._serialized_start=65
  _globals['_STUDENTDETAILS']._serialized_end=422
  _globals['_STUDENTDETAILS_BEHAVIORCOMMENT']._serialized_start=278
  _globals['_STUDENTDETAILS_BEHAVIORCOMMENT']._serialized_end=379
  _globals['_STUDENTDETAILS_LESSON']._serialized_start=381
  _globals['_STUDENTDETAILS_LESSON']._serialized_end=422
# @@protoc_insertion_point(module_scope)
